name: btc_address_validate
version: 0.1.2
description: A minimal library to validate Bitcoin mainnet and testnet addresses
author: Dominik Spicher <dominikspicher@gmail.com>
homepage: https://github.com/dspicher/btc_address_validate

dependencies:
    bech32: ^0.1.2
    base58check: ^2.0.0
    equatable: ^2.0.0

dev_dependencies:
    test: ^1.16.5


environment:
    sdk: ">=2.3.0 <3.0.0"
